# 使用 Ubuntu 22.04 镜像
FROM ubuntu:latest

# 安装 SSH 和其他必要环境
RUN apt-get update && apt-get install -y \
    openssh-server \
    sudo \
    iputils-ping \
    && mkdir /var/run/sshd

# 创建 SSH 用户并设置密码
RUN useradd -m -s /bin/bash dockeruser \
    && echo 'dockeruser:123456' | chpasswd \
    && adduser dockeruser sudo


# 设置工作目录
WORKDIR /home/dockeruser

# 打开 SSH 端口
EXPOSE 22

# 启动 SSH 服务
CMD ["/usr/sbin/sshd", "-D"]
