version: '3.8'

networks:
  transit_net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.254.0.0/24

  # Stub AS Networks
  stub1_net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.1.1.0/24
  stub2_net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.2.1.0/24
  stub3_net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.3.1.0/24
  stub4_net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.4.1.0/24
  stub5_net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.1.0/24

services:
  # transit AS
  transit1_router:
    build: .
    networks:
      transit_net:
        ipv4_address: 10.254.0.2
    volumes:
      - ./config/transit1/bird.conf:/etc/bird/bird.conf
    cap_add: ["NET_ADMIN"]
    privileged: true

  transit2_router:
    build: . 
    networks:
      transit_net:
        ipv4_address: 10.254.0.3
    volumes:
      - ./config/transit2/bird.conf:/etc/bird/bird.conf
    cap_add: ["NET_ADMIN"]
    privileged: true

  # Stub AS
  stub1_router:
    build: .
    networks:
      transit_net:
        ipv4_address: 10.254.0.101
      stub1_net:
        ipv4_address: 10.1.1.254
    volumes:
      - ./config/stub1/bird.conf:/etc/bird/bird.conf
    cap_add: ["NET_ADMIN"]
    privileged: true
  stub1_node1:
    image: ubuntu:latest
    networks:
      stub1_net:
        ipv4_address: 10.1.1.2
  stub1_node2:
    image: ubuntu:latest
    networks:
      stub1_net:
        ipv4_address: 10.1.1.3
    command: sleep infinity
  stub1_node3:
    image: ubuntu:latest
    networks:
      stub1_net:
        ipv4_address: 10.1.1.4
    command: sleep infinity

  stub2_router:
    build: .
    networks:
      transit_net:
        ipv4_address: 10.254.0.102
      stub2_net:
        ipv4_address: 10.2.1.254
    volumes:
      - ./config/stub2/bird.conf:/etc/bird/bird.conf
    cap_add: ["NET_ADMIN"]
    privileged: true

  stub2_node1:
    image: ubuntu:latest
    networks:
      stub2_net:
        ipv4_address: 10.2.1.2
    command: sleep infinity
  stub2_node2:
    image: ubuntu:latest
    networks:
      stub2_net:
        ipv4_address: 10.2.1.3
    command: sleep infinity
  stub2_node3:
    image: ubuntu:latest
    networks:
      stub2_net:
        ipv4_address: 10.2.1.4
    command: sleep infinity

  stub3_router:
    build: .
    networks:
      transit_net:
        ipv4_address: 10.254.0.103
      stub3_net:
        ipv4_address: 10.3.1.254
    volumes:
      - ./config/stub3/bird.conf:/etc/bird/bird.conf
    cap_add: ["NET_ADMIN"]
    privileged: true
  stub3_node1:
    image: ubuntu:latest
    networks:
      stub3_net:
        ipv4_address: 10.3.1.2
    command: sleep infinity
  stub3_node2:
    image: ubuntu:latest
    networks:
      stub3_net:
        ipv4_address: 10.3.1.3
    command: sleep infinity
  stub3_node3:
    image: ubuntu:latest
    networks:
      stub3_net:
        ipv4_address: 10.3.1.4
    command: sleep infinity

  stub4_router:
    build: .
    networks:
      transit_net:
        ipv4_address: 10.254.0.104
      stub4_net:
        ipv4_address: 10.4.1.254
    volumes:
      - ./config/transit1/bird.conf:/etc/bird/bird.conf
    cap_add: ["NET_ADMIN"]
    privileged: true
  stub4_node1:
    image: ubuntu:latest
    networks:
      stub4_net:
        ipv4_address: 10.4.1.2
    command: sleep infinity
  stub4_node2:
    image: ubuntu:latest
    networks:
      stub4_net:
        ipv4_address: 10.4.1.3
    command: sleep infinity
  stub4_node3:
    image: ubuntu:latest
    networks:
      stub4_net:
        ipv4_address: 10.4.1.4
    command: sleep infinity


  stub5_router:
    build: .
    networks:
      transit_net:
        ipv4_address: 10.254.0.105
      stub5_net:
        ipv4_address: 10.5.1.254
    volumes:
      - ./config/transit1/bird.conf:/etc/bird/bird.conf
    cap_add: ["NET_ADMIN"]
    privileged: true

  stub5_node1:
    image: ubuntu:latest
    networks:
      stub5_net:
        ipv4_address: 10.5.1.2
    command: sleep infinity
  stub5_node2:
    image: ubuntu:latest
    networks:
      stub5_net:
        ipv4_address: 10.5.1.3
    command: sleep infinity
  stub5_node3:
    image: ubuntu:latest
    networks:
      stub5_net:
        ipv4_address: 10.5.1.4
    command: sleep infinity